class Fish {
  final String id;
  final String name;
  final String emoji;
  final int difficulty; // 1: 쉬움, 2: 보통, 3: 어려움, 4: 희귀, 5: 전설
  final double speed; // 물고기 이동 속도
  final double size; // 물고기 범위 크기 (0.15 ~ 0.3 - 아이콘이 보일 수 있는 최소 크기 유지)
  final int reward; // 성공 시 포인트 보상
  final String description;
  final String catchMessage; // 포획 메시지
  final double movementPattern; // 움직임 패턴 강도 (0.05 ~ 0.2)

  Fish({
    required this.id,
    required this.name,
    required this.emoji,
    required this.difficulty,
    required this.speed,
    required this.size,
    required this.reward,
    required this.description,
    required this.catchMessage,
    required this.movementPattern,
  });

  static List<Fish> getDummyFishes() {
    return [
      // 쉬움 (100-400벨) - 큰 범위, 느린 속도, 단순한 움직임
      Fish(
        id: 'tadpole',
        name: '올챙이',
        emoji: '🪱',
        difficulty: 1,
        speed: 0.15,
        size: 0.3,
        reward: 5,
        description: '가장 잡기 쉬운 작은 생물',
        catchMessage: '올챙이를 잡았다! 언제 커서 개구리가 될까?',
        movementPattern: 0.05, // 거의 움직이지 않음
      ),
      Fish(
        id: 'frog',
        name: '개구리',
        emoji: '🐸',
        difficulty: 1,
        speed: 0.18,
        size: 0.28,
        reward: 8,
        description: '연못에서 쉽게 만날 수 있는 친구',
        catchMessage: '개구리를 잡았다! 폴짝폴짝!',
        movementPattern: 0.06,
      ),
      Fish(
        id: 'crucian_carp',
        name: '붕어',
        emoji: '🐟',
        difficulty: 1,
        speed: 0.2,
        size: 0.25,
        reward: 10,
        description: '강에서 흔히 볼 수 있는 물고기',
        catchMessage: '붕어를 잡았다! 붕어다! 붕어야!',
        movementPattern: 0.07,
      ),
      Fish(
        id: 'pale_chub',
        name: '피라미',
        emoji: '🐠',
        difficulty: 1,
        speed: 0.25,
        size: 0.24,
        reward: 12,
        description: '작지만 재빠른 물고기',
        catchMessage: '피라미를 잡았다! 흠흠, 조어라고도 한다지?',
        movementPattern: 0.08,
      ),
      Fish(
        id: 'bluegill',
        name: '블루길',
        emoji: '🐟',
        difficulty: 1,
        speed: 0.28,
        size: 0.22,
        reward: 15,
        description: '파란 붕어 같은 외래종',
        catchMessage: '블루길을 잡았다! 파란 붕어 같아!',
        movementPattern: 0.08,
      ),

      // 보통 (500-1000벨) - 중간 범위, 중간 속도, 적당한 움직임
      Fish(
        id: 'dace',
        name: '황어',
        emoji: '🐟',
        difficulty: 2,
        speed: 0.35,
        size: 0.22,
        reward: 20,
        description: '밤에 더 활발한 물고기',
        catchMessage: '황어를 잡았다! 왠지 마이너해!',
        movementPattern: 0.1,
      ),
      Fish(
        id: 'sweetfish',
        name: '은어',
        emoji: '🐠',
        difficulty: 2,
        speed: 0.4,
        size: 0.21,
        reward: 25,
        description: '여름철 별미로 유명한 물고기',
        catchMessage: '은어를 잡았다! 소금에 구워서 먹고 싶어~!!',
        movementPattern: 0.11,
      ),
      Fish(
        id: 'salmon',
        name: '연어',
        emoji: '🐟',
        difficulty: 2,
        speed: 0.42,
        size: 0.2,
        reward: 30,
        description: '바다에서 돌아온 회귀성 물고기',
        catchMessage: '연어를 잡았다! 안녕히 다녀오셨어요?!',
        movementPattern: 0.12,
      ),
      Fish(
        id: 'catfish',
        name: '메기',
        emoji: '😸',
        difficulty: 2,
        speed: 0.38,
        size: 0.21,
        reward: 35,
        description: '멋진 수염을 가진 야행성 물고기',
        catchMessage: '메기를 잡았다! 멋진 수염이군~!',
        movementPattern: 0.1,
      ),

      // 어려움 (1500-5000벨) - 작은 범위, 빠른 속도, 복잡한 움직임
      Fish(
        id: 'king_salmon',
        name: '왕연어',
        emoji: '🐟',
        difficulty: 3,
        speed: 0.5,
        size: 0.19,
        reward: 50,
        description: '연어의 왕! 크고 힘이 센 물고기',
        catchMessage: '예이~~~! 왕연어를 잡았다! 왕! 왕! 왕연어다~!',
        movementPattern: 0.14,
      ),
      Fish(
        id: 'pike',
        name: '강꼬치고기',
        emoji: '🐟',
        difficulty: 3,
        speed: 0.55,
        size: 0.18,
        reward: 60,
        description: '날카로운 이빨을 가진 육식어',
        catchMessage: '강꼬치고기를 잡았다! 날카로운 이빨을 조심해!',
        movementPattern: 0.15,
      ),
      Fish(
        id: 'char',
        name: '열목어',
        emoji: '🐠',
        difficulty: 3,
        speed: 0.52,
        size: 0.18,
        reward: 70,
        description: '깊은 산골 계곡의 귀한 물고기',
        catchMessage: '열목어를 잡았다! 과연 몇살일까?',
        movementPattern: 0.14,
      ),
      Fish(
        id: 'koi',
        name: '비단잉어',
        emoji: '🐠',
        difficulty: 3,
        speed: 0.48,
        size: 0.19,
        reward: 80,
        description: '아름다운 색깔의 고급 잉어',
        catchMessage: '비단잉어를 잡았다! 비, 비싸보여!',
        movementPattern: 0.13,
      ),

      // 희귀 (6000-10000벨) - 최소 범위, 매우 빠른 속도, 매우 복잡한 움직임
      Fish(
        id: 'snapping_turtle',
        name: '늑대거북',
        emoji: '🐢',
        difficulty: 4,
        speed: 0.6,
        size: 0.17,
        reward: 100,
        description: '위험한 턱을 가진 대형 거북',
        catchMessage: '늑대거북을 잡았다! 물리지 않게 조심하자',
        movementPattern: 0.16,
      ),
      Fish(
        id: 'giant_snakehead',
        name: '가물치',
        emoji: '🐍',
        difficulty: 4,
        speed: 0.65,
        size: 0.16,
        reward: 120,
        description: '뱀처럼 생긴 머리의 포악한 물고기',
        catchMessage: '가물치를 잡았다! 머리가 뱀같이 생겼어~!',
        movementPattern: 0.17,
      ),
      Fish(
        id: 'gar',
        name: '가아',
        emoji: '🐊',
        difficulty: 4,
        speed: 0.68,
        size: 0.16,
        reward: 140,
        description: '긴 주둥이를 가진 고대어',
        catchMessage: '가아를 잡았다! 코가 길~어!!',
        movementPattern: 0.17,
      ),
      Fish(
        id: 'arowana',
        name: '아로와나',
        emoji: '🐲',
        difficulty: 4,
        speed: 0.7,
        size: 0.16,
        reward: 160,
        description: '용처럼 생긴 럭셔리한 물고기',
        catchMessage: '아로와나가 잡혔다! 너무 럭셔리해!!',
        movementPattern: 0.18,
      ),
      Fish(
        id: 'arapaima',
        name: '피라루쿠',
        emoji: '🐋',
        difficulty: 4,
        speed: 0.72,
        size: 0.15,
        reward: 180,
        description: '아마존의 거대한 민물고기',
        catchMessage: '피라루쿠를 잡았다! 너무 커서 깜짝!!',
        movementPattern: 0.18,
      ),
      Fish(
        id: 'sturgeon',
        name: '철갑상어',
        emoji: '🐟',
        difficulty: 4,
        speed: 0.75,
        size: 0.15,
        reward: 200,
        description: '캐비아로 유명한 고급 물고기',
        catchMessage: '철갑상어를 잡았다! 캐비아, 캐비아!',
        movementPattern: 0.19,
      ),

      // 전설 (15000벨) - 최소 범위, 극도로 빠른 속도, 극도로 복잡한 움직임
      Fish(
        id: 'dorado',
        name: '도라도',
        emoji: '✨',
        difficulty: 5,
        speed: 0.8,
        size: 0.15,
        reward: 300,
        description: '황금빛으로 빛나는 전설의 물고기',
        catchMessage: '우왓?! 황금물고기...?! 이게 말로만 듣던 도라도? 이섬에서도 잡히는구나~!',
        movementPattern: 0.2, // 매우 불규칙한 움직임
      ),
      Fish(
        id: 'golden_trout',
        name: '금송어',
        emoji: '🌟',
        difficulty: 5,
        speed: 0.82,
        size: 0.15,
        reward: 350,
        description: '눈부시게 아름다운 황금 송어',
        catchMessage: '금송어를 잡았다! 눈부시게 아름다워!',
        movementPattern: 0.2,
      ),
      Fish(
        id: 'stringfish',
        name: '일본연어',
        emoji: '⭐',
        difficulty: 5,
        speed: 0.85,
        size: 0.15,
        reward: 400,
        description: '곰을 삼켰다는 전설의 거대 물고기',
        catchMessage: '우와~~~앗!! 일본연어를 잡았다! 전설의 물고기~~~!!',
        movementPattern: 0.2,
      ),
    ];
  }
}
