// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdF--RG_f0YhX08Zbpj10CzbMXRSVDd18',
    appId: '1:432952540201:web:598ca0a9df57e623643038',
    messagingSenderId: '432952540201',
    projectId: 'samusil-addon',
    authDomain: 'samusil-addon.firebaseapp.com',
    storageBucket: 'samusil-addon.firebasestorage.app',
    measurementId: 'G-SDM6HQ9CFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJV3z2zkJpXl0B81mW2N9lfXHqjDASK7k',
    appId: '1:432952540201:android:2b68c6b9d24e1261643038',
    messagingSenderId: '432952540201',
    projectId: 'samusil-addon',
    storageBucket: 'samusil-addon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFFD-GUW_RAlmRQWxDlQX6UbeUta-kYZ0',
    appId: '1:1087535699794:ios:6386c024bd4af656678c8b',
    messagingSenderId: '1087535699794',
    projectId: 'nippon-life',
    storageBucket: 'nippon-life.appspot.com',
    iosClientId: '1087535699794-t0d8at7782skae9upithhhmusvghb7cv.apps.googleusercontent.com',
    iosBundleId: 'com.lee.nipponlife.nipponLife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdF--RG_f0YhX08Zbpj10CzbMXRSVDd18',
    appId: '1:432952540201:web:13ba09fa865cdf76643038',
    messagingSenderId: '432952540201',
    projectId: 'samusil-addon',
    authDomain: 'samusil-addon.firebaseapp.com',
    storageBucket: 'samusil-addon.firebasestorage.app',
    measurementId: 'G-0KD0HFWB3F',
  );

}