// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAASoZc5szVsXll4sEOJidqAQq7nR3mzVw',
    appId: '1:1087535699794:web:08f29f8006fc722f678c8b',
    messagingSenderId: '1087535699794',
    projectId: 'nippon-life',
    authDomain: 'nippon-life.firebaseapp.com',
    storageBucket: 'nippon-life.appspot.com',
    measurementId: 'G-NSDPZ8XVXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnifq2VT24_8u1UwJ1ChCr2OpdTHz4YlA',
    appId: '1:1087535699794:android:2728fcba9a1c93f2678c8b',
    messagingSenderId: '1087535699794',
    projectId: 'nippon-life',
    storageBucket: 'nippon-life.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFFD-GUW_RAlmRQWxDlQX6UbeUta-kYZ0',
    appId: '1:1087535699794:ios:6386c024bd4af656678c8b',
    messagingSenderId: '1087535699794',
    projectId: 'nippon-life',
    storageBucket: 'nippon-life.appspot.com',
    iosClientId: '1087535699794-t0d8at7782skae9upithhhmusvghb7cv.apps.googleusercontent.com',
    iosBundleId: 'com.lee.nipponlife.nipponLife',
  );
}
